Repository IDeletedSystem64/anitrox, pull requests merged in 2022-03, with the labels that each got.

#42 Upgrade to Stable Release 1.0
  README.md
  commands.md
  commands/8ball.js
  commands/addstatus.js
  commands/avatar.js
  commands/ban.js
  commands/bonk.js
  commands/buttontest.js
  commands/cheese.js
  commands/createserver.js
  commands/cuddle.js
  commands/help.js
  commands/hug.js
  commands/info.js
  commands/invite.js
  commands/kiss.js
  commands/leskiss.js
  commands/lick.js
  commands/nom.js
  commands/opensource.js
  commands/pat.js
  commands/ping.js
  commands/poke.js
  commands/slap.js
  commands/snuggle.js
  commands/uinfo.js
  config-example.json
  icons.json
  releasenotes.txt
  start.js
Labels: enhancement, help wanted, after stable release

#47 Merge @Foxinatel's changes
  commands/8ball.js
  commands/avatar.js
  commands/bonk.js
  commands/cheese.js
  commands/cuddle.js
  commands/eval.js
  commands/help.js
  commands/hug.js
  commands/info.js
  commands/invite.js
  commands/kiss.js
  commands/leskiss.js
  commands/lick.js
  commands/nom.js
  commands/opensource.js
  commands/pat.js
  commands/ping.js
  commands/poke.js
  commands/reload.js
  commands/restart.js
  commands/setnick.js
  commands/slap.js
  commands/snuggle.js
  commands/stop.js
  commands/uinfo.js
  config-example.json
  start.js
Labels: enhancement

#48 Patch the config-printing issue + indentation fix
  commands/avatar.js
  commands/bonk.js
  commands/cheese.js
  commands/cuddle.js
  commands/help.js
  commands/hug.js
  commands/info.js
  commands/invite.js
  commands/kiss.js
  commands/leskiss.js
  commands/lick.js
  commands/nom.js
  commands/opensource.js
  commands/pat.js
  commands/ping.js
  commands/poke.js
  commands/reload.js
  commands/restart.js
  commands/setnick.js
  commands/slap.js
  commands/snuggle.js
  commands/stop.js
  commands/uinfo.js
  start.js
Labels: enhancement

#49 PTB 1.1
  commands/8ball.js
  commands/avatar.js
  commands/bonk.js
  commands/cheese.js
  commands/cuddle.js
  commands/eval.js
  commands/help.js
  commands/hug.js
  commands/info.js
  commands/invite.js
  commands/kiss.js
  commands/leskiss.js
  commands/lick.js
  commands/nom.js
  commands/opensource.js
  commands/pat.js
  commands/ping.js
  commands/poke.js
  commands/reload.js
  commands/restart.js
  commands/setnick.js
  commands/slap.js
  commands/snuggle.js
  commands/stop.js
  commands/uinfo.js
  config-example.json
  start.js
Labels: bug, enhancement

#46 Update to Anitrox 1.1
  commands/8ball.js
  commands/avatar.js
  commands/bonk.js
  commands/cheese.js
  commands/cuddle.js
  commands/eval.js
  commands/help.js
  commands/hug.js
  commands/info.js
  commands/invite.js
  commands/kiss.js
  commands/leskiss.js
  commands/lick.js
  commands/nom.js
  commands/opensource.js
  commands/pat.js
  commands/ping.js
  commands/poke.js
  commands/reload.js
  commands/restart.js
  commands/setnick.js
  commands/slap.js
  commands/snuggle.js
  commands/stop.js
  commands/uinfo.js
  config-example.json
  start.js
Labels: bug, enhancement
