Repository IDeletedSystem64/anitrox, pull requests merged in 2022-04, with the labels that each got.

#50 Fix a small formatting issue and remove deleted emoji
  commands/info.js
Labels: bug

#52 Merge Foxinatels changes with base
  README.md
  commands/8ball.js
  commands/avatar.js
  commands/bonk.js
  commands/cheese.js
  commands/choose.js
  commands/cuddle.js
  commands/eval.js
  commands/help.js
  commands/hug.js
  commands/info.js
  commands/invite.js
  commands/kiss.js
  commands/leskiss.js
  commands/lick.js
  commands/nom.js
  commands/opensource.js
  commands/pat.js
  commands/ping.js
  commands/poke.js
  commands/reload.js
  commands/restart.js
  commands/setnick.js
  commands/slap.js
  commands/snuggle.js
  commands/stop.js
  commands/uinfo.js
  start.js
Labels: enhancement

#53 Upgrade to discord.js v13
  .eslintrc.json
  commands/8ball.js
  commands/avatar.js
  commands/bonk.js
  commands/cheese.js
  commands/choose.js
  commands/contributors.js
  commands/cuddle.js
  commands/eval.js
  commands/help.js
  commands/hug.js
  commands/info.js
  commands/invite.js
  commands/kiss.js
  commands/leskiss.js
  commands/lick.js
  commands/nom.js
  commands/pat.js
  commands/ping.js
  commands/poke.js
  commands/reload.js
  commands/restart.js
  commands/setnick.js
  commands/slap.js
  commands/snuggle.js
  commands/stop.js
  commands/uinfo.js
  config-example.json
  package.json
  start.js
Labels: bug, enhancement
